### ISSUE TITLE
Dark Deception: Monsters & Mortals - Modified Pak File

### ISSUE THREAD

**Issue by AcDinoraus** [FModel/Game-Compatibility#5]
Hello. I would like to report about the issues where the assets of the game's pak file is showing an error when trying to open, view or export through FModel.
Steam Page: https://store.steampowered.com/app/1266690/Dark_Deception_Monsters__Mortals
Unreal Engine Version: 5.1.1.0
![Untitled(3)](https://github.com/FModel/Game-Compatibility/assets/138316096/c10366f0-91d7-4759-accb-d547397cb553)

**Comment by 4sval** [comment]
Q: ***"Package has unversioned properties but mapping file is missing, can't serialize"***
A:
- Generate the appropriate mapping file for the version of the game you load in FModel. You can then set the mapping file in the settings.
https://github.com/OutTheShade/UnrealMappingsDumper

- If you don’t wanna bother with this, use a mapping file from a game that uses the same engine version as yours, but expect errors.
https://github.com/OutTheShade/Unreal-Mappings-Archive

**Comment by AcDinoraus** [comment]
> Q: _**"Package has unversioned properties but mapping file is missing, can't serialize"**_ A:
> 
> * Generate the appropriate mapping file for the version of the game you load in FModel. You can then set the mapping file in the settings.
>   https://github.com/OutTheShade/UnrealMappingsDumper
> * If you don’t wanna bother with this, use a mapping file from a game that uses the same engine version as yours, but expect errors.
>   https://github.com/OutTheShade/Unreal-Mappings-Archive

Injected the Mappings DLL file within the game and it created Mappings.usmap in same Shipping,exe directory as expected.
However, FModel is still giving the same issue. Also, I tried to use the Local Mapping File in the settings but it gave me this error instead.
![Untitled(3)](https://github.com/FModel/Game-Compatibility/assets/138316096/8077e668-c377-4bac-9384-08d4f6f47c30)
